float64 frequency  
int8[] datatypes 
float64[] ee_points
float64[] ee_points_tgt
float64 episode_start_time_in_sec
float64 episode_end_time_in_sec
uint64 T
---
gps_agent_pkg/SampleResult sample_result
